parameters:
  - name: id
    type: string
  - name: type
    type: string
  - name: state
    type: string
  - name: regions
    type: object
    default: ["default"]
  - name: secrets
    type: object
    default: []
  - name: dryrun
    type: boolean
    default: false

stages:
- stage: build_${{ parameters.id }}
  displayName: 'Build ${{ parameters.id }}'

  jobs:
    - ${{ if or(eq(parameters.type,'default'),eq(parameters.type,'bash'),eq(parameters.type,'python'),eq(parameters.type,'container')) }}:
      - ${{ each region in parameters.regions }}:
        - job: build_${{parameters.id}}_${{region}}
          displayName: Build ${{region}}
          steps:

            - template: get-state.yml
              parameters: 
                state: ${{parameters.state}}

            - template: set-state.yml
              parameters:
                id: ${{parameters.id}}
                xt: 'sh'
                env: build 
                stage: build
                region: ${{region}}
                regions: ${{parameters.regions}}
                secrets: ${{parameters.secrets}}

    - ${{ if or(eq(parameters.type,'windows'), eq(parameters.type,'powershell')) }}:
      - ${{ each region in parameters.regions }}:
        - job: build_${{parameters.type}}
          displayName: Build ${{region}}
          steps:
            - template: get-state.yml
              parameters: 
                state: ${{parameters.state}}

            - template: set-state.yml
              parameters:
                id: ${{parameters.id}}
                xt: 'ps1' 
                stage: build
                region: ${{region}}
                regions: ${{parameters.regions}}
                secrets: ${{parameters.secrets}}

    - ${{if eq(parameters.dryrun,false)}}:
      - script: |
          ${APP_COMMAND_INT} "${PRE_SCRIPT} ${PRE_SCRIPT_ARGS}"
          ${APP_COMMAND_INT} "${APP_BUILD_COMMAND} ${APP_BUILD_ARGS}"
          ${APP_COMMAND_INT} "${POST_SCRIPT} ${POST_SCRIPT_ARGS}"
        displayName: BUILD

    - ${{if eq(parameters.dryrun,true)}}:
      - script: |
          echo ${APP_COMMAND_INT} "${PRE_SCRIPT} ${PRE_SCRIPT_ARGS}"
          echo ${APP_COMMAND_INT} "${APP_BUILD_COMMAND} ${APP_BUILD_ARGS}"
          echo ${APP_COMMAND_INT} "${POST_SCRIPT} ${POST_SCRIPT_ARGS}"
        displayName: BUILD (dry run)
