parameters:
  - name: id
    type: string
  - name: env
    type: string
    default: 'dev'
  - name: type
    type: string
    values:
      - openshift
      - windows
      - bash
  - name: dependsOn
    type: string
  - name: regions
    type: object
    default: ['default']
  - name: secrets
    type: object
    default: []
  - name: dryrun
    required: false
    type: boolean
    default: false

stages:
- stage: deploy_${{ parameters.id }}
  displayName: 'Deploy ${{ parameters.id }}'
  dependsOn: ${{ parameters.dependsOn }}

  jobs:
    - ${{ if eq(parameters.type, 'qa-signoff') }}:
      - job: qa_signoff
        displayName: QA Signoff
        steps:
        - script: echo manual qa-signoff

    - ${{ if or((eq(parameters.type,'openshift'),eq(parameters.type,'bash')) }}:
      - ${{ each region in parameters.regions }}:
        - job: deploy_${{parameters.type}}_${{region}}
          displayName: Deploy ${{parameters.type}} ${{region}}
          steps:
          - checkout: templates
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: state
              path: $(System.DefaultWorkingDirectory)/variables

          - script: | 
              python export-state.py deploy_${{parameters.id}}_${{region}} $(System.DefaultWorkingDirectory)/variables/state.ini "$SECRETS" "$REGIONS" 
              chmod +x deploy_${{parameters.id}}_${{region}}.sh && source deploy_${{parameters.id}}_${{region}}.sh 
            displayName: Export state
            workingDirectory: $(System.DefaultWorkingDirectory)/scripts
            env:
              SECRETS: "${{convertToJson(parameters.secrets)}}"
              REGIONS: "${{convertToJson(parameters.regions)}}"

          - script: env | sort
            displayName: List all variables

          - script: echo Deploying...
            displayName: Deploy ${{parameters.type}} ${{region}}
            condition: and(succeeded(), eq(${{ parameters.dryrun }}, false))

          - script: echo Dryrun of deployment...
            displayName: Deploy ${{parameters.type}} ${{region}}
            condition: and(succeeded(), eq(${{ parameters.dryrun }}, true))

    - ${{ if eq(parameters.type, 'windows') }}:
      - job: deploy_${{parameters.type}}
        displayName: Deploy ${{parameters.type}}
        steps:
        - checkout: templates
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: state
            path: $(System.DefaultWorkingDirectory)/variables
        - script: chmod +x export_state.sh && ./export_state.sh ${BUILD_SOURCESDIRECTORY}/variables/state.ini deploy_${{parameters.id}}_${{region}}
          displayName: Export state
          workingDirectory: $(System.DefaultWorkingDirectory)/scripts
        - script: env | sort
          displayName: List all variables
