parameters:
  - name: id
    type: string
  - name: env
    type: string
    default: 'build'
  - name: type
    type: string
  - name: dependsOn
    type: string
  - name: regions
    type: object
    default: ['default']
  - name: secrets
    type: object
    default: []
  - name: dryrun
    type: boolean
    default: false

stages:
- stage: deploy_${{ parameters.id }}
  displayName: 'Deploy ${{ parameters.id }}'
  dependsOn: ${{ parameters.dependsOn }}

  jobs:
    - ${{ if eq(parameters.type, 'qa-signoff') }}:
      - job: qa_signoff
        displayName: QA Signoff
        steps:
        - script: echo manual qa-signoff

    - ${{ if or(eq(parameters.type,'default'),eq(parameters.type,'bash'),eq(parameters.type,'python'),eq(parameters.type,'openshift')) }}:
      - ${{ each region in parameters.regions }}:
        - job: deploy_${{parameters.type}}_${{region}}
          displayName: Deploy ${{region}}
          steps:

            - template: set-state.yml
              parameters:
                id: ${{parameters.id}}
                xt: 'sh'
                env: ${{parameters.env}} 
                stage: deploy
                region: ${{region}}
                regions: ${{parameters.regions}}
                secrets: ${{parameters.secrets}}

            - ${{if eq(parameters.dryrun,false)}}:
              - script: |
                  ${APP_COMMAND_INT} "${PRE_SCRIPT} ${PRE_SCRIPT_ARGS}"
                  ${APP_COMMAND_INT} "${APP_DEPLOY_COMMAND} ${APP_DEPLOY_ARGS}"
                  ${APP_COMMAND_INT} "${POST_SCRIPT} ${POST_SCRIPT_ARGS}"
                displayName: DEPLOY

            - ${{if eq(parameters.dryrun,true)}}:
              - script: |
                  ${APP_COMMAND_INT} "${PRE_SCRIPT} ${PRE_SCRIPT_ARGS}"
                  ${APP_COMMAND_INT} "${APP_DEPLOY_COMMAND} ${APP_DEPLOY_ARGS}"
                  ${APP_COMMAND_INT} "${POST_SCRIPT} ${POST_SCRIPT_ARGS}"
                displayName: DEPLOY (dry run)

    - ${{ if or(eq(parameters.type,'windows'), eq(parameters.type,'powershell')) }}:
      - ${{ each region in parameters.regions }}:
        - job: deploy_${{parameters.type}}_${{region}}
          displayName: Deploy ${{region}}
          steps:

            - template: set-state.yml
              parameters:
                id: ${{parameters.id}}
                xt: 'ps1' 
                env: ${{parameters.env}}
                stage: deploy
                region: ${{region}}
                regions: ${{parameters.regions}}
                secrets: ${{parameters.secrets}}

            - ${{if eq(parameters.dryrun,false)}}:
              - script: |
                  ${APP_COMMAND_INT} "${PRE_SCRIPT} ${PRE_SCRIPT_ARGS}"
                  ${APP_COMMAND_INT} "${APP_DEPLOY_COMMAND} ${APP_DEPLOY_ARGS}"
                  ${APP_COMMAND_INT} "${POST_SCRIPT} ${POST_SCRIPT_ARGS}"
                displayName: DEPLOY

            - ${{if eq(parameters.dryrun,true)}}:
              - script: |
                  ${APP_COMMAND_INT} "${PRE_SCRIPT} ${PRE_SCRIPT_ARGS}"
                  ${APP_COMMAND_INT} "${APP_DEPLOY_COMMAND} ${APP_DEPLOY_ARGS}"
                  ${APP_COMMAND_INT} "${POST_SCRIPT} ${POST_SCRIPT_ARGS}"
                displayName: DEPLOY (dry run)
