parameters:
  - name: id
    type: string
  - name: state
    type: string
  - name: type
    type: string

stages:
- stage: build_${{ parameters.id }}
  displayName: 'Build ${{ parameters.id }}'

  jobs:
    - job: validate
      displayName: Validate
      steps:
        - checkout: templates
        - checkout: self
        
        - script: env | sort
          displayName: List environment variables

        - script: python validate.py $(System.DefaultWorkingDirectory)/${BUILD_REPOSITORY_NAME}/.ado/pipelines.${{ parameters.state}} validation.json variables.ini ${BUILD_STAGINGDIRECTORY}/variables.ini
          displayName: $(System.DefaultWorkingDirectory)
          workingDirectory: $(System.DefaultWorkingDirectory)/templates/validation

    - job: Build
      dependsOn: validate
      steps:
        - script: echo building...
