parameters:
  - name: id
    type: string
  - name: state
    type: string
  - name: type
    type: string

stages:
- stage: build_${{ parameters.id }}
  displayName: 'Build ${{ parameters.id }}'

  jobs:
    - job: validate
      displayName: Validate
      variables:
        - name: system.debug
          value: true
      steps:
        - checkout: templates
        - checkout: self
        
        - script: env | sort
          displayName: List environment variables

        - script: | 
            python validate.py $(System.DefaultWorkingDirectory)/${BUILD_REPOSITORY_NAME}/.ado/pipelines/${{ parameters.state }} validation.json
            echo Validated state:
            echo ...............................................................
            cat state.ini
            echo "##vso[task.setvariable variable=deploymentRegions;isOutput=true]$(cat regions.json)"
          displayName: Validate pipeline
          workingDirectory: $(System.DefaultWorkingDirectory)/templates/scripts/validation

        - publish: $(System.DefaultWorkingDirectory)/templates/scripts/validation/state.ini
          artifact: state

    - job: Build
      dependsOn: validate
      steps:
        - checkout: templates
        - checkout: self

        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: state
            path: $(System.DefaultWorkingDirectory)/variables

        - script: |
            chmod +x export_state.sh
            ./export_state.sh ${BUILD_SOURCESDIRECTORY}/variables/state.ini build_${{parameters.id}}
          displayName: Export state
          workingDirectory: $(System.DefaultWorkingDirectory)/templates/scripts

        - script: env | sort
          displayName: List all variables
