parameters:
  - name: id
    type: string
  - name: state
    type: string
  - name: type
    type: string

stages:
- stage: build_${{ parameters.id }}
  displayName: 'Build ${{ parameters.id }}'

  jobs:
    - job: validate
      displayName: Validate
      variables:
        - name: system.debug
          value: true
      steps:
        - checkout: templates
        - checkout: self
        
        - script: env | sort
          displayName: List environment variables

        - script: python validate.py $(System.DefaultWorkingDirectory)/${BUILD_REPOSITORY_NAME}/.ado/pipelines/${{ parameters.state }} validation.json state.ini
          displayName: Validate pipeline
          workingDirectory: $(System.DefaultWorkingDirectory)/templates/scripts/validation

        - script: | 
            cat $(System.DefaultWorkingDirectory)/templates/scripts/validation/state.ini
          displayName: Validated variables state

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/templates/scripts/validation/state.ini
            artifact: state_variables
            publishLocation: variables

    - job: Build
      dependsOn: validate
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: state_variables
            path: $(System.DefaultWorkingDirectory)/variables
        - script: ls -l
