parameters:
  - name: id
    type: string
  - name: state
    type: string
  - name: type
    type: string

stages:
- stage: build_${{ parameters.id }}
  displayName: 'Build ${{ parameters.id }}'

  jobs:
    - job: validate
      displayName: Validate
      steps:
        - checkout: templates
        - checkout: self
        
        - script: env | sort
          displayName: List environment variables

        - script: python validate.py $(System.DefaultWorkingDirectory)/${BUILD_REPOSITORY_NAME}/.ado/pipelines/${{ parameters.state }} validation.json $(Build.ArtifactStagingDirectory)/variables.ini
          displayName: Validate pipeline
          workingDirectory: $(System.DefaultWorkingDirectory)/templates/scripts/validation

        - script: | 
            cat $(Build.ArtifactStagingDirectory)/variables.ini
          displayName: Validated variables state

        - publish: $(Build.ArtifactStagingDirectory)/variables.ini
          artifact: state        

    - job: Build
      dependsOn: validate
      steps:
        - download: variables
          artifact: state

        - script: ls -l
