parameters:
  - name: id
    type: string
  - name: state
    type: string
  - name: type
    type: string

stages:
- stage: build_${{ parameters.id }}
  displayName: 'Build ${{ parameters.id }}'

  jobs:
    - job: validate
      displayName: Validate
      steps:
        - checkout: templates
        - checkout: self
        
        - script: env | sort
          displayName: List environment variables

        - script: pwd && ls -l
          displayName: $(System.DefaultWorkingDirectory)
          workingDirectory: $(System.DefaultWorkingDirectory)

    - job: Build
      dependsOn: validate
      steps:
        - script: echo building...
