parameters:
  - name: id
    type: string
  - name: env
    type: string
    default: 'dev'
  - name: type
    type: string
  - name: dependsOn
    type: string
  - name: secrets
    type: object
    default: []

stages:
- stage: deploy_${{ parameters.id }}
  displayName: 'Deploy ${{ parameters.id }}'
  dependsOn: ${{ parameters.dependsOn }}

  jobs:
  - job: deploy
    displayName: Deploy
    steps:

    - script: env | sort 
      displayName: List all variables

    - download: state
      artifact: variables

    - script: ./export_state.sh $(System.DefaultWorkingDirectory)/variables/state.ini
      displayName: Export state variables
      workingDirectory: $(System.DefaultWorkingDirectory)/templates/scripts

    - script: env | sort 
      displayName: List all variables
