parameters:
  - name: id
    type: string
  - name: type
    type: string
  - name: dependsOn
    type: string
  - name: secrets
    type: object
    default: []

stages:
- stage: deploy_${{ parameters.id }}
  displayName: 'Deploy ${{ parameters.id }}'
  dependsOn: ${{ parameters.dependsOn }}

  jobs:
  - job: Deploy
    steps:
    - script: |
        echo Deploying!
      displayName: Deploy
