parameters:
  - name: id
    type: string
  - name: env
    type: string
    default: 'dev'
  - name: type
    type: string
  - name: dependsOn
    type: string
  - name: secrets
    type: object
    default: []

stages:
- stage: deploy_${{ parameters.id }}
  displayName: 'Deploy ${{ parameters.id }}'
  dependsOn: ${{ parameters.dependsOn }}

  jobs:
  - job: deploy
    displayName: Deploy
    steps:
    - checkout: templates
    - checkout: self

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: state
        path: $(System.DefaultWorkingDirectory)/variables

    - script: |
        chmod +x export_state.sh
        ./export_state.sh ${BUILD_SOURCESDIRECTORY}/variables/state.ini deploy_${{parameters.id}}
      displayName: Export state
      workingDirectory: $(System.DefaultWorkingDirectory)/templates/scripts

    - script: env | sort
      displayName: List all variables
