resources:
  repositories:
    - repository: self
      clean: true
    - repository: templates
      type: github
      endpoint: github-templates
      name: earnestdl/templates
      ref: refs/heads/main
                     
trigger:
  batch: true
  branches:
    include:
      - hotfix/*
      - feature/*
      - develop
      - master
      - main
pr:
  branches:
    include:
      - develop
      - master
      - main

stages:

  - template: .azuredevops/pipelines/build.yml@templates
    parameters:
      id: app
      state: variables-regions.json
      type: container

  - template: .azuredevops/pipelines/deploy.yml@templates
    parameters:
      id: dev
      env: dev
      type: openshift
      dependsOn: build_app
      regions: ['east', 'west']
      secrets:
        "OPENSHIFT_TOKEN_EAST": "$(OPENSHIFT_TOKEN_DEV_EAST)"
        "OPENSHIFT_TOKEN_WEST": "$(OPENSHIFT_TOKEN_DEV_WEST)"

  - template: .azuredevops/pipelines/test.yml@templates
    parameters:
      id: unit
      type: unit
      dependsOn: build_app

  - template: .azuredevops/pipelines/deploy.yml@templates
    parameters:
      id: qa
      env: qa
      type: openshift
      dependsOn: test_unit
      regions: ['east', 'west']
      secrets:
        "OPENSHIFT_TOKEN_EAST": "$(OPENSHIFT_TOKEN_QA_EAST)"
        "OPENSHIFT_TOKEN_WEST": "$(OPENSHIFT_TOKEN_QA_WEST)"

  - template: .azuredevops/pipelines/deploy.yml@templates
    parameters:
      id: stress
      env: stress
      type: openshift
      dependsOn: deploy_qa
      regions: ['east', 'west']
      secrets:
        "OPENSHIFT_TOKEN_EAST": "$(OPENSHIFT_TOKEN_STRESS_EAST)"
        "OPENSHIFT_TOKEN_WEST": "$(OPENSHIFT_TOKEN_STRESS_WEST)"

  - template: .azuredevops/pipelines/deploy.yml@templates
    parameters:
      id: qa_signoff
      type: qa-signoff
      dependsOn: deploy_stress

  - template: .azuredevops/pipelines/deploy.yml@templates
    parameters:
      id: prod
      env: prod
      type: openshift
      dependsOn: deploy_qa_signoff
      regions: ['east', 'west']
      secrets:
        "OPENSHIFT_TOKEN_EAST": "$(OPENSHIFT_TOKEN_PROD_EAST)"
        "OPENSHIFT_TOKEN_WEST": "$(OPENSHIFT_TOKEN_PROD_WEST)"
