resources:
  repositories:
    - repository: self
      clean: true
    - repository: templates
      type: github
      endpoint: github-templates
      name: earnestdl/templates
      ref: refs/heads/main
                     
trigger:
  batch: true
  branches:
    include:
      - hotfix/*
      - feature/*
      - develop
      - master
      - main
pr:
  branches:
    include:
      - develop
      - master
      - main

variables:
  - group: secrets-flask

stages:

  - template: .ado/pipelines/build.yml@templates
    parameters:
      id: asdf
      state: variables-openshift.json
      type: container

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: dev
      env: dev
      type: openshift
      dependsOn: build_default
      secrets:
        OPENSHIFT_TOKEN_EAST: $(OPENSHIFT_TOKEN_DEV_E1)
        OPENSHIFT_TOKEN_WEST: $(OPENSHIFT_TOKEN_DEV_E2)
        API_KEY: $(API_KEY_DEV)

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: qa
      env: qa
      type: openshift
      dependsOn: deploy_dev
      secrets:
        OPENSHIFT_TOKEN_EAST: $(OPENSHIFT_TOKEN_QA_E1)
        OPENSHIFT_TOKEN_WEST: $(OPENSHIFT_TOKEN_QA_E2)
        API_KEY: $(API_KEY_QA)

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: stress
      env: stress
      type: openshift
      dependsOn: deploy_qa
      secrets:
        OPENSHIFT_TOKEN_EAST: $(OPENSHIFT_TOKEN_QA_E1)
        OPENSHIFT_TOKEN_WEST: $(OPENSHIFT_TOKEN_QA_E2)
        API_KEY: $(API_KEY_QA)

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: qa_signoff
      type: qa-signoff
      dependsOn: deploy_stress

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: prod
      env: prod
      type: openshift
      dependsOn: deploy_qa_signoff
      secrets:
        OPENSHIFT_TOKEN_EAST: $(OPENSHIFT_TOKEN_PROD_E1)
        OPENSHIFT_TOKEN_WEST: $(OPENSHIFT_TOKEN_PROD_E2)
        API_KEY: $(API_KEY_PROD)
