resources:
  repositories:
    - repository: self
      clean: true
    - repository: templates
      type: github
      endpoint: github-templates
      name: earnestdl/templates
      ref: refs/heads/main
                     
trigger:
  batch: true
  branches:
    include:
      - hotfix/*
      - feature/*
      - develop
      - master
      - main
pr:
  branches:
    include:
      - develop
      - master
      - main

stages:

  - template: .ado/pipelines/build.yml@templates
    parameters:
      id: default
      state: variables-openshift.json
      type: container

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: dev
      env: dev
      type: registry
      dependsOn: build_default

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: qa
      env: qa
      type: registry
      dependsOn: deploy_dev

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: stress
      env: stress
      type: registry
      dependsOn: deploy_qa

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: qa_signoff
      type: qa-signoff
      dependsOn: deploy_stress

  - template: .ado/pipelines/deploy.yml@templates
    parameters:
      id: prod
      env: prod
      type: registry
      dependsOn: deploy_qa_signoff
