  on: 
    workflow_call: 
      inputs:
        appVersion: 
          required: true
          type: string

jobs:
  Build-BASH:
    runs-on: ubuntu-latest
    env:
      APPTYPE: bash
      APPVERSION: ${{ inputs.appVersion }}
    steps:
      - name: "List Variables"
        run: | 
          echo hello from BASH build template
          echo appType: $APPTYPE
          echo appVersion: $APPVERSION
