on: 
  workflow_call: 
    inputs:
      appType:
        required: true
        type: string
      appVersion: 
        required: true
        type: string

jobs:
  Stage-Build:
    runs-on: ubuntu-latest
    steps:
      - name: "List Variables"
        run: | 
          echo hello from build stage template
          echo appType: $APPTYPE
          echo appVersion: $APPVERSION
        env:
          APPTYPE: ${{ inputs.appType }}
          APPVERSION: ${{ inputs.appVersion }}
      
