on: 
  workflow_call: 
    inputs:
      id:
        required: true
        type: string
      type: 
        required: true
        type: string
      state:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    name: validate
    steps:
    - name: run script
      run: echo validating pipeline

    - name: list all variables
      run: env | sort
