on: 
  workflow_call: 
    inputs:
      appType:
        required: true
        type: string
      appVersion: 
        required: true
        type: string

jobs:
  Build:
    uses: earnestdl/templates/.github/workflows/${{ inputs.appType }}.yml@main
    with: 
      appVersion: ${{ inputs.appVersion }}
      
