on: 
  workflow_call: 
    inputs:
      id:
        required: true
        type: string
      type: 
        required: true
        type: string
      env:
        required: true
        type: string
      regions: 
        required: false
        type: string
        default: '["default"]'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - region: ${{ fromJson(inputs.regions)[0] }}
    steps:
      - name: Set Random Region if Default
        if: matrix.region == 'default'
        run: |
          # Define your regions here
          REGIONS=("east" "west")
          # Select a random region
          RANDOM_REGION=${REGIONS[$RANDOM % ${#REGIONS[@]}]}
          echo "RANDOM_REGION=$RANDOM_REGION" >> $GITHUB_ENV

      - name: Deploy
        run: |
          REGION=${{ env.RANDOM_REGION || matrix.region }}
          echo "Deploying to ${{ inputs.env }} in $REGION region"
          # Add the deployment script or command here