on: 
  workflow_call: 
    inputs:
      id:
        required: true
        type: string
      type: 
        required: true
        type: string
      env:
        required: true
        type: string
      regions: 
        required: false
        type: string
        default: '["default"]'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - name: Set Random Region
        if: ${{ inputs.regions == '["default"]' }}
        id: random_region
        run: |
          # Define your regions here
          REGIONS=("east" "west")
          # Select a random region
          RANDOM_REGION=${REGIONS[$RANDOM % ${#REGIONS[@]}]}
          echo "REGION=$RANDOM_REGION" >> $GITHUB_ENV

      - name: Deploy
        run: |
          REGION=${{ steps.random_region.outputs.region || matrix.region }}
          echo "Deploying to ${{ inputs.env }} in $REGION region"