on: 
  workflow_call: 
    inputs:
      id:
        required: true
        type: string
      type: 
        required: true
        type: string
      env:
        required: true
        type: string
      regions: 
        required: true
        type: string
        default: '[]'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.env }} in ${{ matrix.region }} region"
