on: 
  workflow_call: 
    inputs:
      deployEnvironment: 
        required: true
        type: string
      deployRegions: 
        required: true
        type: string

jobs:
  Deploy-OpenShift:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployRegions: ${{ fromJson(inputs.deployRegions) }}
    env:
      TARGET: openshift
      ENV: ${{ inputs.deployEnvironment }}
    steps:
      - name: "List Variables"
        run: | 
          echo hello from OpenShift Deploy template
          echo deployTarget: openshift
          echo deployEnvironment: $ENV

      - name: Compliance
        uses: earnestdl/templates/.github/workflows/compliance.yml@main
        with:
          event: postdeploy
