on: 
  workflow_call: 
    inputs:
      event:
        required: true
        type: string

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      APPTYPE: bash
      event: ${{ inputs.event }}
    steps:
      - name: "List Variables"
        run: env | sort

      - name: Validate
        run: | 
          echo hello from Validation template
          echo event: $event
 